package com.nexis.obuluyor.repository

import com.nexis.obuluyor.model.Advert
import com.nexis.obuluyor.util.AppUtils
import io.reactivex.Single
import retrofit2.http.Field

class AddNewAdvertRepository {
    fun addNewAdvert(
        userId: Int,
        userPhone: Int?,
        message: Int?,
        advertTitle: String?,
        advertContent: String?,
        advertType: Int?,
        advertPrice: Int?,
        advertExchange: String?,
        cargoPrice: Int?,
        cargoArrive: Int?,
        advertCargo: String?,
        advertCountry: Int,
        advertCity: Int,
        advertLocality: Int,
        advertLat: String?,
        advertLng: String?,
        advertZoom: String?,
        advertConfirm: Int?,
        advertDates: String?,
        advertCategories: String,
        advertStream: Int?,
        advertFinishDate: String?,
        advertPrice2: String?,
        advertPrice3: String?,
        advertFinishFullDate: String?,
        advertPay: Int?,
        companyName: String?,
        phone: String?,
        fax: String?,
        gsm: String?,
        web: String?,
        taxAdmin: String?,
        taxNo: String?,
        createDate: String?,
        businessType: String?,
        director: String?,
        endorsement: String?,
        employeesAmount: String?,
        about: String?,
        adres: String?,
        viewAmount: Int?,
        priceDown: String?,
        moduleContentIdData: String,
        moduleContentNameData: String,
        moduleIdData: String,
        moduleClassData: String,
        propIdData: String,
        propValData: String
    ) : Single<Advert> {
        return AppUtils.getAppAPI().addNewAdvert(
            userId,
            userPhone,
            message,
            advertTitle,
            advertContent,
            advertType,
            advertPrice,
            advertExchange,
            cargoPrice,
            cargoArrive,
            advertCargo,
            advertCountry,
            advertCity,
            advertLocality,
            advertLat,
            advertLng,
            advertZoom,
            advertConfirm,
            advertDates,
            advertCategories,
            advertStream,
            advertFinishDate,
            advertPrice2,
            advertPrice3,
            advertFinishFullDate,
            advertPay,
            companyName,
            phone,
            fax,
            gsm,
            web,
            taxAdmin,
            taxNo,
            createDate,
            businessType,
            director,
            endorsement,
            employeesAmount,
            about,
            adres,
            viewAmount,
            priceDown,
            moduleContentIdData,
            moduleContentNameData,
            moduleIdData,
            moduleClassData,
            propIdData,
            propValData
        )
    }
}